document.addEventListener("DOMContentLoaded", function() {
    // Fetch the JSON generated by Python
    fetch('dashboard_data.json')
        .then(response => response.json())
        .then(data => {
            renderDashboard(data);
        })
        .catch(err => console.error("Error loading data:", err));
});

function renderDashboard(data) {
    // 1. Update KPI Cards
    document.getElementById('kpi-mae').innerText = data.metrics.mae;
    document.getElementById('kpi-rmse').innerText = data.metrics.rmse;
    document.getElementById('kpi-cov').innerText = data.metrics.coverage + "%";
    document.getElementById('kpi-samples').innerText = data.metrics.samples;

    const commonLayout = {
        paper_bgcolor: 'rgba(0,0,0,0)',
        plot_bgcolor: 'rgba(0,0,0,0)',
        font: { color: '#e5e5e5' },
        margin: { t: 30, l: 40, r: 20, b: 40 },
        xaxis: { gridcolor: '#333' },
        yaxis: { gridcolor: '#333' }
    };

    // Tool 1: Main Forecast Chart
    const traceActual = {
        x: data.time_series.date,
        y: data.time_series.actual,
        mode: 'lines',
        name: 'Actual',
        line: { color: '#9ca3af', width: 1 }
    };
    const tracePred = {
        x: data.time_series.date,
        y: data.time_series.pred,
        mode: 'lines',
        name: 'Forecast',
        line: { color: '#3b82f6', width: 2 }
    };
    const traceUpper = {
        x: data.time_series.date,
        y: data.time_series.upper,
        mode: 'lines',
        name: 'Upper Bound',
        line: { width: 0 },
        showlegend: false
    };
    const traceLower = {
        x: data.time_series.date,
        y: data.time_series.lower,
        fill: 'tonexty',
        mode: 'lines',
        name: 'Confidence Interval',
        line: { width: 0 },
        fillcolor: 'rgba(59, 130, 246, 0.2)'
    };

    Plotly.newPlot('chart-main', [traceActual, traceUpper, traceLower, tracePred], commonLayout);

    // Tool 2: Residual Histogram
    Plotly.newPlot('chart-resid-hist', [{
        x: data.time_series.residuals,
        type: 'histogram',
        marker: { color: '#f59e0b' }
    }], commonLayout);

    // Tool 3: Scatter Plot
    const maxVal = Math.max(...data.time_series.actual);
    const minVal = Math.min(...data.time_series.actual);
    Plotly.newPlot('chart-scatter', [
        {
            x: data.time_series.actual,
            y: data.time_series.pred,
            mode: 'markers',
            type: 'scatter',
            marker: { color: '#10b981', size: 3, opacity: 0.5 }
        },
        {
            x: [minVal, maxVal],
            y: [minVal, maxVal],
            mode: 'lines',
            line: { color: 'white', dash: 'dash' }
        }
    ], { ...commonLayout, showlegend: false });

    // Tool 4: Feature Importance
    Plotly.newPlot('chart-features', [{
        x: data.features.scores.reverse(),
        y: data.features.names.reverse(),
        type: 'bar',
        orientation: 'h',
        marker: { color: '#8b5cf6' }
    }], { ...commonLayout, margin: { l: 150, t: 10, b: 30 } });

    // Tool 5: Baselines
    if (data.baselines.names) {
        Plotly.newPlot('chart-baseline', [{
            x: data.baselines.names,
            y: data.baselines.mae,
            type: 'bar',
            marker: { color: ['#10b981', '#6b7280', '#6b7280', '#6b7280', '#6b7280'] } 
        }], commonLayout);
    }

    // Tool 6: Residuals Over Time
    Plotly.newPlot('chart-resid-time', [{
        x: data.time_series.date,
        y: data.time_series.residuals,
        mode: 'lines',
        line: { color: '#ef4444', width: 1 }
    }], commonLayout);

    // Tool 7: Heteroscedasticity (Pred vs Residuals)
    Plotly.newPlot('chart-hetero', [{
        x: data.time_series.pred,
        y: data.time_series.residuals,
        mode: 'markers',
        marker: { size: 2, color: '#f59e0b' }
    }], { ...commonLayout, xaxis: {title: 'Predicted Value'}, yaxis: {title: 'Error'} });

    // Tool 8: Interval Width
    const width = data.time_series.upper.map((u, i) => u - data.time_series.lower[i]);
    Plotly.newPlot('chart-width', [{
        x: data.time_series.date,
        y: width,
        mode: 'lines',
        fill: 'tozeroy',
        line: { color: '#06b6d4', width: 1 }
    }], commonLayout);

    // Tool 9: Cumulative Error (Squared)
    let cumSum = 0;
    const cumError = data.time_series.residuals.map(r => {
        cumSum += (r * r);
        return cumSum;
    });
    Plotly.newPlot('chart-cumulative', [{
        x: data.time_series.date,
        y: cumError,
        mode: 'lines',
        line: { color: '#ec4899' }
    }], commonLayout);

    // Tool 10: Table (Last 50 rows)
    const tbody = document.getElementById('table-body');
    const len = data.time_series.date.length;
    const start = Math.max(0, len - 50); // Show last 50
    
    for (let i = len - 1; i >= start; i--) {
        let row = `<tr>
            <td>${data.time_series.date[i]}</td>
            <td>${data.time_series.actual[i].toFixed(5)}</td>
            <td class="text-primary">${data.time_series.pred[i].toFixed(5)}</td>
            <td class="text-muted">${data.time_series.lower[i].toFixed(5)}</td>
            <td class="text-muted">${data.time_series.upper[i].toFixed(5)}</td>
            <td class="${data.time_series.residuals[i] > 0 ? 'text-success' : 'text-danger'}">
                ${data.time_series.residuals[i].toFixed(5)}
            </td>
        </tr>`;
        tbody.innerHTML += row;
    }
}
